### ISSUE TITLE
Use of uninitialized value $params[0] in pattern match (m//) at /usr/share/perl5/Email/Valid.pm line 78.

### ISSUE THREAD

**Issue by GDesclaux** [rjbs/Email-Valid#14]
Hi,

In some cases, there is an error reported during execution of this module : 

Use of uninitialized value $params[0] in pattern match (m//) at /usr/share/perl5/Email/Valid.pm line 78.

To prevent this, the line 76 should be changed from

return %args unless @params;

to

return %args unless defined $params[0];

**Comment by rjbs** [comment]
(see #15 instead)
