### ISSUE TITLE
MX check throws error

### ISSUE THREAD

**Issue by graeme83** [rjbs/Email-Valid#20]
Using Email::Valid 1.197 and Net::DNS version 1.02

    if (!Email::Valid->address($emailaddress, -mxcheck => 1)){
    print "Invalid Email";
    }

    Can't call method "answer" on an undefined value at /usr/local/lib/perl5/site_perl/5.14.2/Email/Valid.pm line 153.

Works fine with previous version.  The problem line is

     my $query = $Resolver->search($mx);

I think that maybe should be

     my $query = $Resolver->search($mxhost);

**Comment by tmorehouse** [comment]
You are Correct.  that was a typo on my part in my fork.

**Comment by rjbs** [comment]
Thanks for the report, cutting a new release right now!
